name: core_location_fluttify
description: A new Flutter project.
version: 0.2.4
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/core_location_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.8.10
  latlng: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.core_location_fluttify
        pluginClass: CoreLocationFluttifyPlugin
      ios:
        pluginClass: CoreLocationFluttifyPlugin